-- Redesign data model: workout title and location, set timestamps and
-- manually logged workouts. Additive only, so existing rows and older app
-- builds keep working.

alter table public.workouts
  add column title text,
  add column location_type text,
  add column place_name text,
  add column place_address text,
  add column place_lat double precision,
  add column place_lng double precision;

alter table public.workouts
  add constraint workouts_location_type_check
    check (location_type in ('Gym', 'Home', 'Park', 'Other')),
  add constraint workouts_place_requires_name_check
    check (
      place_name is not null
      or (place_address is null and place_lat is null and place_lng is null)
    ),
  add constraint workouts_place_coordinates_check
    check ((place_lat is null) = (place_lng is null));

-- Added without a default first so existing sets keep a null timestamp
-- instead of all being stamped with the time this migration ran.
alter table public.exercise_sets
  add column created_at timestamptz;
alter table public.exercise_sets
  alter column created_at set default now();

create table public.manual_workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  date date not null,
  title text not null check (length(title) > 0),
  location_type text not null
    check (location_type in ('Gym', 'Home', 'Park', 'Other')),
  place_name text,
  place_address text,
  place_lat double precision,
  place_lng double precision,
  created_at timestamptz not null default now(),
  constraint manual_workouts_place_requires_name_check
    check (
      place_name is not null
      or (place_address is null and place_lat is null and place_lng is null)
    ),
  constraint manual_workouts_place_coordinates_check
    check ((place_lat is null) = (place_lng is null))
);

create index manual_workouts_user_id_date_idx
  on public.manual_workouts (user_id, date desc);

alter table public.manual_workouts enable row level security;

revoke all on table public.manual_workouts from anon, authenticated;
grant select, insert, update, delete
  on table public.manual_workouts
  to authenticated;
grant select, insert, update, delete
  on table public.manual_workouts
  to service_role;

revoke all on sequence public.manual_workouts_id_seq from anon, authenticated;
grant usage, select
  on sequence public.manual_workouts_id_seq
  to authenticated;
grant usage, select
  on sequence public.manual_workouts_id_seq
  to service_role;

create policy "Users can read their manual workouts"
  on public.manual_workouts
  for select
  to authenticated
  using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can create their manual workouts"
  on public.manual_workouts
  for insert
  to authenticated
  with check (
    (select auth.uid()) is not null and (select auth.uid()) = user_id
  );

create policy "Users can update their manual workouts"
  on public.manual_workouts
  for update
  to authenticated
  using ((select auth.uid()) is not null and (select auth.uid()) = user_id)
  with check (
    (select auth.uid()) is not null and (select auth.uid()) = user_id
  );

create policy "Users can delete their manual workouts"
  on public.manual_workouts
  for delete
  to authenticated
  using ((select auth.uid()) is not null and (select auth.uid()) = user_id);
